//
//  DetailInteractor.swift
//  PRACTICA_CACTUS911
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailInteractor {
    //MARK: - Protocol Properties
    weak var presenter: DetailPresenterProtocol?
}

//MARK: - Interactor Methods
extension DetailInteractor: DetailInteractorProtocol {
    
}
