//
//  HomeProtocols.swift
//  PRACTICA_CACTUS911
//
//  Created Administrator on 02/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {
    func celdaSelect(detail: Result)
}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {
    func getData(Typee: Typee)
    func info(informacion: Welcome)
    func celdaSelect(detail: Result)
}

//MARK: Interactor -
protocol HomeInteractorProtocol: AnyObject {
 
  var presenter: HomePresenterProtocol?  { get set }
    func getInitData(type: Typee)
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {
    func info(informacion: Welcome)
  var presenter: HomePresenterProtocol?  { get set }
}
