//
//  HomePresenter.swift
//  PRACTICA_CACTUS911
//
//  Created Administrator on 02/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter {
    //MARK: - Protocol Properties
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    //MARK: - Life Cycle
    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension HomePresenter: HomePresenterProtocol {
    func celdaSelect(detail: Result) {
        print("detailSelecPresenter::::: \(detail)")
        router.celdaSelect(detail: detail)
    }
    
    func info(informacion: Welcome) {
        view?.info(informacion: informacion)
        print("la info esta en el presenter \(informacion)")
    }
    
    func getData(Typee: Typee) {
        interactor?.getInitData(type: Typee)
    }
    
}

//MARK: - Private functions
extension HomePresenter {
    
}
